/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.BloodBankManagerRole;

import Business.EcoSystem;
import Business.Organization.BloodBMOrganz;
import Business.Organization.LabOrg;
import Business.Organization.Org;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.PatientTreatmentWR;
import Business.WorkQueue.WR;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author arundathi
 */
public class BBManagerWAJPanel extends javax.swing.JPanel {

    private JPanel jPanel;
    private EcoSystem ecosystem;
    private UserAccount usrAcnt;
    private BloodBMOrganz bloodBankMngrOrg;

    /**
     * Creates new form LabAssistantWorkAreaJPanel
     */
    public BBManagerWAJPanel(JPanel userProcessContainer, UserAccount account, Org organization, EcoSystem business) {
        initComponents();

        this.jPanel = userProcessContainer;
        this.usrAcnt = account;
        this.ecosystem = business;
        this.bloodBankMngrOrg = (BloodBMOrganz) organization;

        pplTbl();
    }

    public void pplTbl() {
        DefaultTableModel model = (DefaultTableModel) wrkReqJTable.getModel();

        model.setRowCount(0);


        for (WR request : bloodBankMngrOrg.getWrkQ().getWorkRequests()) {

            Object[] row = new Object[7];
            row[0] = request;
            row[1] = request.getSender().getEmp().getEmpName();
            row[2] = ((PatientTreatmentWR) request).getBloodBankManager();
            row[3] = request.getStatus();
            row[4] = ((PatientTreatmentWR ) request).getPat().getPatFrstNm() + " " + ((PatientTreatmentWR) request).getPat().getPatLstNm();
            row[5] = ((PatientTreatmentWR) request).getPat().getPatId();
            row[6]=((PatientTreatmentWR) request).getBloodUnits();
            model.addRow(row);
        }
        TableRowSorter<DefaultTableModel> sorter = new TableRowSorter<>(model);
        wrkReqJTable.setRowSorter(sorter);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        wrkReqJTable = new javax.swing.JTable();
        asgnJButton = new javax.swing.JButton();
        prcsJButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 255, 204));
        setLayout(null);

        wrkReqJTable.setBackground(new java.awt.Color(204, 204, 204));
        wrkReqJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Message", "Sender", "Receiver", "Status", "Patient Name", "Patient Id", "Blood Units"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(wrkReqJTable);

        add(jScrollPane1);
        jScrollPane1.setBounds(10, 20, 730, 90);

        asgnJButton.setBackground(new java.awt.Color(204, 204, 204));
        asgnJButton.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        asgnJButton.setText("Assign to me");
        asgnJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                asgnJButtonActionPerformed(evt);
            }
        });
        add(asgnJButton);
        asgnJButton.setBounds(190, 130, 140, 40);

        prcsJButton.setBackground(new java.awt.Color(204, 204, 204));
        prcsJButton.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        prcsJButton.setText("Process");
        prcsJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prcsJButtonActionPerformed(evt);
            }
        });
        add(prcsJButton);
        prcsJButton.setBounds(370, 130, 140, 40);
    }// </editor-fold>//GEN-END:initComponents

    private void asgnJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_asgnJButtonActionPerformed

        int selectedRow = wrkReqJTable.getSelectedRow();

        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null,"Please start by selecting a row.");
            return;
        }

        PatientTreatmentWR request = (PatientTreatmentWR) wrkReqJTable.getValueAt(selectedRow, 0);
        if (request.getBloodBankManager() == null) {
            if (request.getStatus().equalsIgnoreCase("SentToBloodBank")) {
                request.setBloodBankManager(usrAcnt);
                request.setStatus("Pending on Blood Bank");
                //  request.setReceiver(userAccount);
                pplTbl();
                JOptionPane.showMessageDialog(null, "The request has been assigned to You!");
            } else {
                JOptionPane.showMessageDialog(null, "This lab request cannot be assigned because its current status is: " + request.getStatus());
            }
        }
        else
        {

            if(usrAcnt.equals(request.getLabAst()))

            {
                JOptionPane.showMessageDialog(null,"You have already been assigned to the request.");
            }
            else
            {
                JOptionPane.showMessageDialog(null, "Request is assigned to other Lab Assistant");
            }
        }

    }//GEN-LAST:event_asgnJButtonActionPerformed

    private void prcsJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prcsJButtonActionPerformed

        int selectedRow = wrkReqJTable.getSelectedRow();

        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please select a row");
            return;
        }

        PatientTreatmentWR request = (PatientTreatmentWR) wrkReqJTable.getValueAt(selectedRow, 0);

       // request.setStatus("Processing");
        BloodProcessWRJPanel processWorkRequestJPanel = new BloodProcessWRJPanel(jPanel, request);
        if (request.getBloodBankManager() != null) {
            if (usrAcnt.equals(request.getBloodBankManager())) {
                if (request.getStatus().equalsIgnoreCase("Pending on Blood Bank")) {

                    jPanel.add("processWorkRequestJPanel", processWorkRequestJPanel);
                    CardLayout layout = (CardLayout) jPanel.getLayout();
                    layout.next(jPanel);
                } else {
                    JOptionPane.showMessageDialog(null, "The request cannot be processed because the status is: " + request.getStatus());
                }

            } else {

                JOptionPane.showMessageDialog(null, " To request, you must be an authorized user.");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Please assign the request first");
        }
    }//GEN-LAST:event_prcsJButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton asgnJButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton prcsJButton;
    private javax.swing.JTable wrkReqJTable;
    // End of variables declaration//GEN-END:variables
}
