/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.BloodBankManagerRole;


import Business.WorkQueue.PatientTreatmentWR;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import userinterface.BloodBankManagerRole.BBManagerWAJPanel;

/**
 *
 * @author arundathi
 */
public class BloodProcessWRJPanel extends javax.swing.JPanel {

    JPanel jPanel;
    PatientTreatmentWR ptTrWrReq;

    /**
     * Creates new form ProcessWorkRequestJPanel
     */
    public BloodProcessWRJPanel(JPanel userProcessContainer, PatientTreatmentWR patientTreatmentWorkRequest) {
        initComponents();
        this.jPanel = userProcessContainer;
        this.ptTrWrReq = patientTreatmentWorkRequest;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sbmtJButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        rsltMsgJTextField = new javax.swing.JTextField();
        backJButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 255, 204));
        setLayout(null);

        sbmtJButton.setBackground(new java.awt.Color(204, 204, 204));
        sbmtJButton.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        sbmtJButton.setText("Submit Result");
        sbmtJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sbmtJButtonActionPerformed(evt);
            }
        });
        add(sbmtJButton);
        sbmtJButton.setBounds(240, 170, 117, 36);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setText("Message");
        add(jLabel1);
        jLabel1.setBounds(170, 110, 60, 17);
        add(rsltMsgJTextField);
        rsltMsgJTextField.setBounds(250, 100, 160, 30);

        backJButton.setBackground(new java.awt.Color(204, 204, 204));
        backJButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        backJButton.setText(" Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        add(backJButton);
        backJButton.setBounds(20, 20, 72, 20);

        jLabel2.setFont(new java.awt.Font("Telugu MN", 1, 24)); // NOI18N
        jLabel2.setText("Blood Bank");
        add(jLabel2);
        jLabel2.setBounds(230, 30, 195, 30);
    }// </editor-fold>//GEN-END:initComponents

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed

        jPanel.remove(this);
        Component[] componentArray = jPanel.getComponents();
        Component component = componentArray[componentArray.length - 1];
        BBManagerWAJPanel dwjp = (BBManagerWAJPanel) component;
        dwjp.pplTbl();
        CardLayout layout = (CardLayout) jPanel.getLayout();
        layout.previous(jPanel);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void sbmtJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sbmtJButtonActionPerformed
        String bloodBankMessage = rsltMsgJTextField.getText().trim();
        if (bloodBankMessage.equals("")) {
            JOptionPane.showMessageDialog(null, "Result is Required!");
            return;
        } else {
            int dialogResult = JOptionPane.showConfirmDialog(null, "Do you wish to continue?");
            if (dialogResult == JOptionPane.YES_OPTION) {
                ptTrWrReq.setBloodBankMessage(bloodBankMessage);
                ptTrWrReq.setStatus("Blood Bank Request successful");
                JOptionPane.showMessageDialog(null, "Result submitted successfully");
                rsltMsgJTextField.setText("");
                sbmtJButton.setEnabled(false);
            }

        }


    }//GEN-LAST:event_sbmtJButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField rsltMsgJTextField;
    private javax.swing.JButton sbmtJButton;
    // End of variables declaration//GEN-END:variables
}
