package userinterface.AdministrativeRole;

import userinterface.NGOAdministratorRole.NGOAdminWorkAreaPanel;
import Business.EcoSystem;
import Business.Enterprise.En;
import Business.Enterprise.GovtEn;
import Business.Enterprise.InsurancecmpnyEN;
import Business.Enterprise.NGOEn;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author bhuvana
 */
public class EnAdminWAJPanel extends javax.swing.JPanel {

    JPanel jPanel;
    En entrpz;
    UserAccount usrAc;
    EcoSystem ecosystem;

    /**
     * Creates new form AdminWorkAreaJPanel
     */
    public EnAdminWAJPanel(JPanel userProcessContainer, En enterprise, UserAccount userAccount, EcoSystem ecoSystem) {
        initComponents();
        this.jPanel = userProcessContainer;
        this.entrpz = enterprise;
        this.usrAc = userAccount;
        this.ecosystem = ecoSystem;
        valueLabel.setText(enterprise.getName());

        if (enterprise instanceof GovtEn || enterprise instanceof InsurancecmpnyEN
            || enterprise instanceof NGOEn ) {
            btnGovtFundReq.setVisible(false);
            btnNGOFundReq.setVisible(false);

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        mnguserJButton = new javax.swing.JButton();
        mngEmpJButton = new javax.swing.JButton();
        mngOrgJButton = new javax.swing.JButton();
        enterpriseLabel = new javax.swing.JLabel();
        valueLabel = new javax.swing.JLabel();
        btnGovtFundReq = new javax.swing.JButton();
        btnNGOFundReq = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 255, 204));

        jLabel1.setFont(new java.awt.Font("Telugu MN", 1, 24)); // NOI18N
        jLabel1.setText("Admin Role");

        mnguserJButton.setBackground(new java.awt.Color(204, 204, 204));
        mnguserJButton.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        mnguserJButton.setText("Manage User");
        mnguserJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnguserJButtonActionPerformed(evt);
            }
        });

        mngEmpJButton.setBackground(new java.awt.Color(204, 204, 204));
        mngEmpJButton.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        mngEmpJButton.setText("Manage Employee");
        mngEmpJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mngEmpJButtonActionPerformed(evt);
            }
        });

        mngOrgJButton.setBackground(new java.awt.Color(204, 204, 204));
        mngOrgJButton.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        mngOrgJButton.setText("Manage Organization");
        mngOrgJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mngOrgJButtonActionPerformed(evt);
            }
        });

        enterpriseLabel.setFont(new java.awt.Font("Telugu MN", 1, 18)); // NOI18N
        enterpriseLabel.setText("Enterprise :");

        valueLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        btnGovtFundReq.setBackground(new java.awt.Color(204, 204, 204));
        btnGovtFundReq.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnGovtFundReq.setText("Request Funds from Government");
        btnGovtFundReq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGovtFundReqActionPerformed(evt);
            }
        });

        btnNGOFundReq.setBackground(new java.awt.Color(204, 204, 204));
        btnNGOFundReq.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnNGOFundReq.setText("Request Funds from NGO");
        btnNGOFundReq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNGOFundReqActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(196, 196, 196)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(enterpriseLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(valueLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(46, 46, 46)
                                .addComponent(jLabel1)))
                        .addContainerGap(167, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(mngEmpJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mngOrgJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mnguserJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnGovtFundReq)
                            .addComponent(btnNGOFundReq, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(valueLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(enterpriseLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addComponent(mngOrgJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addComponent(mngEmpJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(mnguserJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnGovtFundReq, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnNGOFundReq, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(131, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void mnguserJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnguserJButtonActionPerformed
        // TODO add your handling code here:
        ManageUAJPanel muajp = new ManageUAJPanel(jPanel, entrpz);
        jPanel.add("ManageUserAccountJPanel", muajp);

        CardLayout layout = (CardLayout) jPanel.getLayout();
        layout.next(jPanel);
    }//GEN-LAST:event_mnguserJButtonActionPerformed

    private void mngEmpJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mngEmpJButtonActionPerformed


        ManageEmplyJPanel manageEmployeeJPanel = new ManageEmplyJPanel(jPanel, entrpz.getOrgDir());
        jPanel.add("manageEmployeeJPanel", manageEmployeeJPanel);


        CardLayout layout = (CardLayout) jPanel.getLayout();
        layout.next(jPanel);

    }//GEN-LAST:event_mngEmpJButtonActionPerformed

    private void mngOrgJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mngOrgJButtonActionPerformed


        ManageOrgJPanel manageOrganizationJPanel = new ManageOrgJPanel(jPanel, entrpz.getOrgDir(), entrpz);
        jPanel.add("manageOrganizationJPanel", manageOrganizationJPanel);
        CardLayout layout = (CardLayout) jPanel.getLayout();
        layout.next(jPanel);
    }//GEN-LAST:event_mngOrgJButtonActionPerformed


    private void btnGovtFundReqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGovtFundReqActionPerformed
        CardLayout layout = (CardLayout) jPanel.getLayout();
        jPanel.add("RequestFundsJPanel", new RequestFundsJPanel(jPanel, entrpz, usrAc, ecosystem));
        layout.next(jPanel);
    }//GEN-LAST:event_btnGovtFundReqActionPerformed

    private void btnNGOFundReqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNGOFundReqActionPerformed
        // TODO add your handling code here:
       CardLayout layout = (CardLayout) jPanel.getLayout();
        jPanel.add("NGORequestFundsJPanel", new NGORequestFundsJPanel(jPanel, entrpz, usrAc, ecosystem));
        layout.next(jPanel);
    }//GEN-LAST:event_btnNGOFundReqActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGovtFundReq;
    private javax.swing.JButton btnNGOFundReq;
    private javax.swing.JLabel enterpriseLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton mngEmpJButton;
    private javax.swing.JButton mngOrgJButton;
    private javax.swing.JButton mnguserJButton;
    private javax.swing.JLabel valueLabel;
    // End of variables declaration//GEN-END:variables

}
