/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.AdministrativeRole;

import Business.EcoSystem;
import Business.Enterprise.En;
import Business.Network.Network;
import Business.Organization.HCOfficerOrganz;
import Business.Organization.Org;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.GovtFundRequest;
import Business.WorkQueue.WR;
import java.awt.CardLayout;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author arundathi
 */
public class RequestFundsJPanel extends javax.swing.JPanel {

    private JPanel jPanel;
    private En entrpz;
    private UserAccount usrAc;
    private EcoSystem ecoSystem;

    /**
     * Creates new form RequestFundsJPanel
     */
    public RequestFundsJPanel(JPanel jPanel, En enterprise, UserAccount userAccount, EcoSystem ecoSystem) {
        initComponents();
        this.jPanel = jPanel;
        this.entrpz = enterprise;
        this.usrAc = userAccount;
        this.ecoSystem = ecoSystem;
        pplTbl();
    }

    public void pplTbl() {
        DefaultTableModel model = (DefaultTableModel) workRequestJTable.getModel();
        double totalFunds = 0;
        model.setRowCount(0);

        for (WR request : usrAc.getWrkQ().getWorkRequests()) {

            if(request instanceof GovtFundRequest){
            Object[] row = new Object[4];
            row[0] = String.valueOf(((GovtFundRequest) request).getLocation());
            row[1] = request.getReceiver();
            row[2] = request.getStatus();
            row[3] = String.valueOf(((GovtFundRequest) request).getReqAmt());
            model.addRow(row);
            if (request.getStatus().equalsIgnoreCase("Accepted")) {
                totalFunds += ((GovtFundRequest) request).getReqAmt();
            }
            }
        }

        txtFundsReceived.setText(String.valueOf(totalFunds));
        TableRowSorter<DefaultTableModel> sorter = new TableRowSorter<>(model);
        workRequestJTable.setRowSorter(sorter);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblRequestFunds = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtLocation = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtpopulation = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtAmount = new javax.swing.JTextField();
        btnSendFundRequest = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        workRequestJTable = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtFundsReceived = new javax.swing.JTextField();
        backJButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 255, 204));
        setLayout(null);

        lblRequestFunds.setFont(new java.awt.Font("Telugu MN", 1, 24)); // NOI18N
        lblRequestFunds.setText("Request Funds");
        add(lblRequestFunds);
        lblRequestFunds.setBounds(236, 11, 228, 50);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setText("Location: ");
        add(jLabel1);
        jLabel1.setBounds(67, 69, 70, 17);

        txtLocation.setBackground(new java.awt.Color(204, 204, 204));
        txtLocation.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtLocation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLocationActionPerformed(evt);
            }
        });
        add(txtLocation);
        txtLocation.setBounds(165, 67, 141, 23);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setText("Population:");
        add(jLabel2);
        jLabel2.setBounds(67, 107, 72, 17);

        txtpopulation.setBackground(new java.awt.Color(204, 204, 204));
        txtpopulation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpopulationActionPerformed(evt);
            }
        });
        add(txtpopulation);
        txtpopulation.setBounds(165, 105, 143, 23);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setText("Amount:");
        add(jLabel3);
        jLabel3.setBounds(67, 145, 60, 17);

        txtAmount.setBackground(new java.awt.Color(204, 204, 204));
        txtAmount.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtAmount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAmountActionPerformed(evt);
            }
        });
        add(txtAmount);
        txtAmount.setBounds(165, 143, 143, 23);

        btnSendFundRequest.setBackground(new java.awt.Color(204, 204, 204));
        btnSendFundRequest.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnSendFundRequest.setText("Request");
        btnSendFundRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendFundRequestActionPerformed(evt);
            }
        });
        add(btnSendFundRequest);
        btnSendFundRequest.setBounds(160, 180, 160, 38);

        workRequestJTable.setBackground(new java.awt.Color(204, 204, 204));
        workRequestJTable.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        workRequestJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Location", "Receiver", "Status", "Amount"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(workRequestJTable);

        add(jScrollPane1);
        jScrollPane1.setBounds(40, 360, 592, 97);

        jLabel4.setFont(new java.awt.Font("Telugu MN", 1, 12)); // NOI18N
        jLabel4.setText("All Funds Requests");
        add(jLabel4);
        jLabel4.setBounds(270, 310, 124, 36);

        jLabel5.setFont(new java.awt.Font("Telugu MN", 1, 12)); // NOI18N
        jLabel5.setText("Total Funds Received :");
        add(jLabel5);
        jLabel5.setBounds(40, 230, 128, 15);

        txtFundsReceived.setEditable(false);
        txtFundsReceived.setBackground(new java.awt.Color(204, 204, 204));
        txtFundsReceived.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        add(txtFundsReceived);
        txtFundsReceived.setBounds(180, 230, 143, 23);

        backJButton.setBackground(new java.awt.Color(204, 204, 204));
        backJButton.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        backJButton.setText(" Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        add(backJButton);
        backJButton.setBounds(30, 20, 90, 23);
    }// </editor-fold>//GEN-END:initComponents

    private void txtLocationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLocationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLocationActionPerformed

    private void txtpopulationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpopulationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpopulationActionPerformed

    private void txtAmountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAmountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAmountActionPerformed

    private void btnSendFundRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendFundRequestActionPerformed

        String location = txtLocation.getText().trim();
        String population = txtpopulation.getText();
        String amount = txtAmount.getText();
        if (location.equals("") || population.equals("") || amount.equals("")) {
            JOptionPane.showMessageDialog(null, "All fields are mandatory");
        } else {
            try {
                Integer.parseInt(population);
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(null, "Please type an Integer value for population");
                return;
            }
            try {
                Double.parseDouble(amount);
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(null, "Please type an Integer value for amount");
                return;
            }
            GovtFundRequest governmentFundRequest = new GovtFundRequest(location, Integer.parseInt(population), Double.parseDouble(amount));
            governmentFundRequest.setSender(usrAc);
            governmentFundRequest.setStatus("Sent");

            Org org = null;

            List<Network> networks = ecoSystem.getNetworks();

            for (Network network : networks) {

                List<En> enterprises = network.getEntDir().getEntList();
                for (En enterprise : enterprises) {
                    List<Org> organizations = enterprise.getOrgDir().getOrganizations();
                    for (Org organization : organizations) {
                        if (organization instanceof HCOfficerOrganz) {
                            org = organization;
                            break;
                        }
                    }
                }
            }

            if (org != null) {

                org.getWrkQ().getWorkRequests().add(governmentFundRequest);
                usrAc.getWrkQ().getWorkRequests().add(governmentFundRequest);

            }
            pplTbl();
        }
    }//GEN-LAST:event_btnSendFundRequestActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        jPanel.remove(this);
        CardLayout layout = (CardLayout) jPanel.getLayout();
        layout.previous(jPanel);
    }//GEN-LAST:event_backJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton;
    private javax.swing.JButton btnSendFundRequest;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblRequestFunds;
    private javax.swing.JTextField txtAmount;
    private javax.swing.JTextField txtFundsReceived;
    private javax.swing.JTextField txtLocation;
    private javax.swing.JTextField txtpopulation;
    private javax.swing.JTable workRequestJTable;
    // End of variables declaration//GEN-END:variables
}
