/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.DoctorRole;

import Business.Enterprise.En;
import Business.Organization.LabOrg;
import Business.Organization.Org;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.PatientTreatmentWR;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author bhuvana
 */
public class RequestLTJPanel extends javax.swing.JPanel {

    private JPanel jPanel;
    private En entrpz;
    private UserAccount usrAcnt;
    private PatientTreatmentWR pntTrmntWrReq;

    /**
     * Creates new form RequestLabTestJPanel
     */
    public RequestLTJPanel(JPanel userProcessContainer, UserAccount account, En enterprise, PatientTreatmentWR patientTreatmentWorkRequest) {
        initComponents();

        this.jPanel = userProcessContainer;
        this.entrpz = enterprise;
        this.usrAcnt = account;
        this.pntTrmntWrReq = patientTreatmentWorkRequest;
        valueLabel.setText(enterprise.getName());
        requestTestJButton.setEnabled(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        requestTestJButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtLabMessage = new javax.swing.JTextField();
        backJButton = new javax.swing.JButton();
        valueLabel = new javax.swing.JLabel();
        enterpriseLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtLabType = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 255, 204));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        requestTestJButton.setBackground(new java.awt.Color(204, 204, 204));
        requestTestJButton.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        requestTestJButton.setText("Request Test");
        requestTestJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                requestTestJButtonActionPerformed(evt);
            }
        });
        add(requestTestJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 240, 130, 30));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setText("Message:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 190, 70, -1));
        add(txtLabMessage, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 180, 130, 30));

        backJButton.setBackground(new java.awt.Color(204, 204, 204));
        backJButton.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        backJButton.setText("Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        add(backJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, 30));

        valueLabel.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        valueLabel.setText("<value>");
        add(valueLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 80, 130, 20));

        enterpriseLabel.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        enterpriseLabel.setText("Enterprise :");
        add(enterpriseLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, 90, 20));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setText("Lab Type:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 150, -1, -1));
        add(txtLabType, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 140, 130, 30));

        jLabel3.setFont(new java.awt.Font("Telugu MN", 1, 18)); // NOI18N
        jLabel3.setText("Lab Test Request ");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 30, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void requestTestJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_requestTestJButtonActionPerformed

        String labType = txtLabType.getText().trim();
        String message = txtLabMessage.getText().trim();

        if (labType.equals("")) {
            JOptionPane.showMessageDialog(null, "Field is Required");
            return;
        }
        if (message.equals("")) {
            JOptionPane.showMessageDialog(null, "Field is Required");
            return;
        }


        pntTrmntWrReq.setLabTstMsg(message);
        pntTrmntWrReq.setSender(usrAcnt);
        pntTrmntWrReq.setStatus("SentToLab");
        pntTrmntWrReq.setReceiver(null);

        Org org = null;
        for (Org organization : entrpz.getOrgDir().getOrganizations()) {

            if (organization instanceof LabOrg) {
                org = organization;
                break;
            }
        }
        if (org != null) {

            org.getWrkQ().getWorkRequests().add(pntTrmntWrReq);
            usrAcnt.getWrkQ().getWorkRequests().add(pntTrmntWrReq);

            JOptionPane.showMessageDialog(null, "Lab request sent");
            txtLabMessage.setText("");
            txtLabType.setText("");
            requestTestJButton.setEnabled(false);
        }

    }//GEN-LAST:event_requestTestJButtonActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed

        jPanel.remove(this);
        Component[] componentArray = jPanel.getComponents();
        Component component = componentArray[componentArray.length - 1];
        DoctorWAJPanel dwjp = (DoctorWAJPanel) component;
        dwjp.pplReqTbl();
        CardLayout layout = (CardLayout) jPanel.getLayout();
        layout.previous(jPanel);

    }//GEN-LAST:event_backJButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton;
    private javax.swing.JLabel enterpriseLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton requestTestJButton;
    private javax.swing.JTextField txtLabMessage;
    private javax.swing.JTextField txtLabType;
    private javax.swing.JLabel valueLabel;
    // End of variables declaration//GEN-END:variables
}
